
WITH source_data AS (
    SELECT
       id
       ,created_by
       ,created_date
       ,modified_by
       ,modified_date
       ,buyer_freeze
       ,buyer_id
       ,certification_body_freeze
       ,certification_body_id
       ,certification_id
       ,certifier_comment
       ,consignees_freeze
       ,contracting_office_id
       ,customer_remarks
       ,docstore_id
       ,inspection_body_freeze
       ,inspection_body_id
       ,issued_at
       ,last_processor_freeze
       ,last_processor_id
       ,po_number
       ,program_group_id
       ,program_id
       ,seller_freeze
       ,seller_id
       ,shipper_id
       ,status
       ,type
       ,valid
       ,organization_id
       ,shipment_id
       ,shipper_freeze
       ,certificate_id
       ,issued_by
       ,verified_by
       ,migrated
       ,in_conversion
       ,status_changed_at
       ,tc_workflow_instance_id
       ,is_producer
       ,gross_weight
       ,net_weight
       ,recipient_id
       ,recipient_freeze
       ,buyer_license_number
       ,additional_data
       ,outsource_to_subcontractor
       ,non_certified_trader_name
       ,seller_license_number
       ,seller_sc_number
       ,copied_from
       ,buyer_is_certified
       ,accepted_terms
       ,multi_shipment_agreement
       ,amendment_reason
       ,artwork_claims
       ,financial_check
       ,original_tc_issued_at
       ,accept_acknowledgement
       ,approve_tc_expired_sc_confirmation
       ,request_tc_expired_sc_confirmation
       ,has_warnings
       ,requested_by
       ,amendment_tc_id
       ,icu_tc_number
       ,standard_tc_number
       ,MAX(_peerdb_synced_at)                 AS _peerdb_synced_at
    FROM {{ source('icu_connected', 'tc') }} AS tc
    WHERE _peerdb_is_deleted = FALSE
    GROUP BY
        id
        ,created_by
        ,created_date
        ,modified_by
        ,modified_date
        ,buyer_freeze
        ,buyer_id
        ,certification_body_freeze
        ,certification_body_id
        ,certification_id
        ,certifier_comment
        ,consignees_freeze
        ,contracting_office_id
        ,customer_remarks
        ,docstore_id
        ,inspection_body_freeze
        ,inspection_body_id
        ,issued_at
        ,last_processor_freeze
        ,last_processor_id
        ,po_number
        ,program_group_id
        ,program_id
        ,seller_freeze
        ,seller_id
        ,shipper_id
        ,status
        ,type
        ,valid
        ,organization_id
        ,shipment_id
        ,shipper_freeze
        ,certificate_id
        ,issued_by
        ,verified_by
        ,migrated
        ,in_conversion
        ,status_changed_at
        ,tc_workflow_instance_id
        ,is_producer
        ,gross_weight
        ,net_weight
        ,recipient_id
        ,recipient_freeze
        ,buyer_license_number
        ,additional_data
        ,outsource_to_subcontractor
        ,non_certified_trader_name
        ,seller_license_number
        ,seller_sc_number
        ,copied_from
        ,buyer_is_certified
        ,accepted_terms
        ,multi_shipment_agreement
        ,amendment_reason
        ,artwork_claims
        ,financial_check
        ,original_tc_issued_at
        ,accept_acknowledgement
        ,approve_tc_expired_sc_confirmation
        ,request_tc_expired_sc_confirmation
        ,has_warnings
        ,requested_by
        ,amendment_tc_id
        ,icu_tc_number
        ,standard_tc_number
)

SELECT
    *
FROM source_data